# Configuración general
title: "Hattrick Hub"
description: "El centro de acceso a todas las herramientas y recursos de Hattrick."
url: "https://hattrick-hub.github.io"
baseurl: ""
lang: es
image: /assets/img/hub.png
permalink: /:title/
theme: null
author: elPatronHT
color: "#1d4ed8"

# Procesamiento de Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

# Configuración de enlaces relativos
relative_links:
  enabled: true
  collections: true

# Exclusiones
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .git/
  - .github/
  - .gitignore
  - vendor/
  - _site/
  - .DS_Store
  - src/
  - package.json
  - yarn.lock

# Colecciones
collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  manual:
    output: true
    permalink: /manual/:title/
  noticias:
    output: true
    permalink: /noticias/:title/
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      author: elPatronHT
  - scope:
      path: ""
      type: blog
    values:
      layout: blog-post
      image: /assets/img/placeholder.png
  - scope:
      path: ""
      type: manual
    values:
      layout: manual-post
      image: /assets/img/placeholder.png
  - scope:
      path: ""
      type: noticias
    values:
      layout: noticias-post
      image: /assets/img/placeholder.png
  - scope:
      path: ""
      type: pages
    values:
      layout: default
