# CONFIGURACIÓN GENERAL
title: "Hattrick Hub"
description: "El centro de acceso a todas las herramientas y recursos de Hattrick."
url: "https://hattrick-hub.github.io"
baseurl: ""
lang: es
timezone: America/Bogota
image: /assets/img/placeholder.webp
permalink: /:title/
author: elPatronHT
author_team_url: "https://hattrick.org/goto.ashx?path=/Club/?TeamID=538167"
color: "#4B8A61"

# MARKDOWN
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# PLUGINS
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-redirect-from

# ENLACES RELATIVOS
relative_links:
  enabled: true
  collections: true

# FEED 
feed:
  posts_limit: 20
  excerpt_only: true

strict_front_matter: true

# EXCLUSIONES
exclude:
  - .DS_Store
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site/
  - node_modules/
  - package.json
  - src/
  - vendor/
  - yarn.lock
  - scripts/
  - assets/img/raw/
  - .jekyll-cache/

# COLECCIONES
collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  manual:
    output: true
    permalink: /manual/:title/
  noticias:
    output: true
    permalink: /noticias/:title/
  herramientas:
    output: true
    permalink: /herramientas/:title/
  pages:
    output: true
    permalink: /:name/

# VALORES POR DEFECTO
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: elPatronHT
      lang: es
      image: /assets/img/placeholder.webp
      twitter:
        card: summary_large_image
  - scope:
      path: ""
      type: blog
    values:
      layout: blog-post
  - scope:
      path: ""
      type: manual
    values:
      layout: manual-post
  - scope:
      path: ""
      type: noticias
    values:
      layout: noticias-post
  - scope:
      path: ""
      type: herramientas
    values:
      layout: herramientas-post
  - scope:
      path: ""
      type: pages
    values:
      layout: default